### ISSUE TITLE
Request for updating node version

### ISSUE THREAD

**Issue by sabertazimi** [sunzongzheng/musicApi#1]
Is there any specific reason node version should be `8.x`?

**Comment by sunzongzheng** [comment]
https://github.com/sunzongzheng/musicApi/blob/34cbde5ed4db0268431e4ed209d9306eff83068f/.babelrc#L7

It should be upward compatible. Does it not work on node v10 ?

**Comment by sabertazimi** [comment]
I can't install this package via `npm install @suen/music-api` due to:
https://github.com/sunzongzheng/musicApi/blob/34cbde5ed4db0268431e4ed209d9306eff83068f/package.json#L17

**Comment by sabertazimi** [comment]
I think `"node": ">=8.x"` would be better if there isn't any other specific reason that this package can't work on `node v9/v10/v11`.

**Comment by sunzongzheng** [comment]
> 9.9.0

![image](https://user-images.githubusercontent.com/12635613/48314545-0dc4e580-e606-11e8-8b63-c3b2d5704778.png)
Could you paste the error log?

**Comment by sabertazimi** [comment]
- windows 10
- node v9.9.0
- work fine on `npm`, but broken on `yarn`

![image](https://user-images.githubusercontent.com/12670482/48314653-57fa9680-e607-11e8-952d-ed05f2becca5.png)

**Comment by sunzongzheng** [comment]
It should work fine now, thx pr
