### ISSUE TITLE
React Native 中 searchSong 获取不到网易云音乐的数据

### ISSUE THREAD

**Issue by JohnSmith0602** [sunzongzheng/musicApi#11]
昨天晚上多次调用 musicApi.searchSong('好久不见')，返回的结果中 qq 和 xiami 下的返回结果都正常，而 netease 的返回是 { total: 0, songs: [] }。怀疑是不是网易云音乐的接口又调整了。

谢谢～

**Comment by sunzongzheng** [comment]
![image](https://user-images.githubusercontent.com/12635613/65738127-682e3e00-e113-11e9-8450-ab18b58e6c7e.png)
我这边测试正常，`多次`具体是大概多少次？我以前for循环调用网易云接口的时候被ban过ip，一周左右才恢复。你现在能访问 https://music.163.com 吗

**Comment by JohnSmith0602** [comment]
那就很奇怪，我昨天的操作是从 RN 端第一次调用 searchSong 的时候 netease 的返回就是空，调用了几次都是空（qq 和 xiami 的返回结果都正常），我试了关键词'好久不见'和'一生所爱'，而且之后我立刻去 https://music.163.com 手动搜索之后，返回结果也是正常的。
我待会再试一下吧。

P.S. https://music.163.com 一直是可以访问的。

**Comment by sunzongzheng** [comment]
![image](https://user-images.githubusercontent.com/12635613/65738732-6f564b80-e115-11e9-861d-8c590b87a588.png)
我发现了问题，第一次和最后一次都是没有开启react native的debug模式，会获取不到数据，中间的部分都是开启了debug，获取正常。
我排查一下问题~

**Comment by sunzongzheng** [comment]
按[文档](https://github.com/sunzongzheng/musicApi#%E5%BC%95%E5%85%A5)说明重新引入

**Comment by JohnSmith0602** [comment]
我按照文档重新引入之后还是不行，在 Xcode 里能看到报了一个 「Secure random number generation is not supported by this browser」的错误。
而且很奇怪的是，musicApi.searchSong(keyword).then(console.warn).catch(console.warn)，现在直接是没有任何响应了，而不是像之前只是返回结果里是空。
另外我在新环境试 musicApi.xiami.searchSong，还是照常工作的。

我待会再看一下吧。

**Comment by JohnSmith0602** [comment]
我在 randombytes 相关的内容下找了半天，照其中最接近的一个 [issue](https://github.com/tradle/rn-nodeify/issues/58) 中说的两个要点来操作：

- 项目依赖全部安装好后再跑 rn-nodify 脚本；
- 使用了 rnctest 项目的 shim.js 文件（那个 demo 用 npm i 死活不成功...）

结果都不能解决问题，现象仍同上一条留言一样。而且按照这个 hack node in RN 的思路，项目依赖被写的一团乱，看上去每装一个新依赖还得 re-run rn-nodify 脚本。

所以我打算单开一个 node server 提供 musicApi 好了，正好我需要做定制化的需求，之前还打算 fork 这个库重新发布的，现在这些工作都可以在 node server 做了，提供给 App 和 Web 多端一致的服务。完美～

@sunzongzheng 最后想问下你按照这个方案是跑通了的是吗？抱歉我就不花精力继续受折磨了... 如果你需要我提供什么调试信息是可以的！

**Comment by JohnSmith0602** [comment]
突然想到，暂时先不考虑服务器的性能问题，如果所有的 musicApi 请求都从服务器发起，是不是更容易被识别成爬虫呢？不知道现在的库实现里有做代理机制避免被反爬虫吗？

**Comment by sunzongzheng** [comment]
我再次更新了文档，在全新的 react-native-cli生成的项目下测试通过。

看rn-nodify的文档，我的理解是，如果希望 重新根据当前的依赖 生成hack脚本，才需要需要重新执行rn-nodify，如果新依赖没有node原生模块，应该不需要。

提供公共的api server确实会导致请求量过大时被ban ip，建议请求从客户端发。
经过我的测试，当服务可能频繁重启时，最容易触发虾米的反爬机制，由于虾米请求接口需要获取key，稍微频繁的获取key，就会触发。虾米的key会缓存在内存，重启服务后就会重新获取，所以不要频繁重新服务。其次是网易云，触发反爬后会被ban ip一周左右。

以下代码可以手动给某个vendor的请求加上代理
````js
musicApi[vendor].instance.config.proxy = 'http://localhost:8080'
````

**Comment by JohnSmith0602** [comment]
@sunzongzheng 我刚把 node_modules 清空，重新 yarn，再按照你的文档操作，还是不行。（其实早上除了是用 npm，其它操作也一样）也许和 RN 版本有关吧，或者是其它原因...

除了之前提到的原因，我下午又想到一个很重要的点，App 更新比站点更新要麻烦得多，音乐服务印象中时不时就改接口反爬虫，我觉得把 musicApi 嵌在应用里面不是一个灵活的方案。至于说 api server 的问题，碰到了再解决吧。谢谢分享经验。

**Comment by sunzongzheng** [comment]
`Secure random number generation is not supported by this browser`依然报这个错应该是没有更新最新代码的原因，你那边有更新最新代码吗，我还没有发布新的npm版本，需要先从github拉最新代码 

````shell
yarn remove @suen/music-api
yarn add github:sunzongzheng/musicApi
````

**Comment by JohnSmith0602** [comment]
@sunzongzheng 我以为你的 commit 只是改了文档，不需要改项目代码呢！我也拿到网易云音乐的数据了～（虽然还是决定起个 api server...

非常感谢这么及时的响应！

**Comment by sunzongzheng** [comment]
好的，那就证明rn中确实可以用了，感谢提供信息~
