### ISSUE TITLE
musicApi.searchSong 能不能也支持 musicApi.qq.searchSong 的 searchSongOptions 参数格式？

### ISSUE THREAD

**Issue by JohnSmith0602** [sunzongzheng/musicApi#12]
我在使用 musicApi.searchSong 的时候也有指定 limit 的需求，结果发现现在的参数格式 (keyword, offset) 似乎是不支持的，searchSong(options: searchSongOptions) 这种格式是我想要的。
另外，musicApi.searchSong 和 musicApi.qq.searchSong 的参数格式完全不同，我在使用之初也是挺困惑的。
能不能在保留现有参数的前提下，给 musicApi.searchSong 也支持以 searchSongOptions 对象为参数呢？

**Comment by sunzongzheng** [comment]
musicApi起初的目的是实现简便的调用方式，但是维护到目前看来其实意义是不大的，所以v2版本里会直接干掉，只支持musicApi[vendor]的方式调用。如果你目前有这个需求的话建议直接重写原方法
````js
musicApi.searchSong = function () {
  // ...
}
````

**Comment by JohnSmith0602** [comment]
嗯，那我在自己的代码里封装一层～
