### ISSUE TITLE
How can use this api in android  

### ISSUE THREAD

**Issue by yasser9372** [sunzongzheng/musicApi#13]
Hi.
I am new in using APIs, I want to use this API to search and stream musics in an android application using java or kotlin. Can i use this API using retrofit or some thing similar? If it's possible, which steps i need to do this?

thanks.

**Comment by sunzongzheng** [comment]
You can see the specific usage in the following repository. The general process is that Android loads js in the webview and then calls the js function in Android by bridging.
 https://github.com/caiyonglong/MusicLake
