### ISSUE TITLE
qq源 放不出来了

### ISSUE THREAD

**Issue by lokve** [sunzongzheng/musicApi#14]
qq源 不管什么音质都不能播放

**Comment by sunzongzheng** [comment]
经过测试，web版的接口已经不能获取web版无法试听的歌曲url，需要寻找新的办法

**Comment by wednesday** [comment]
https://u.y.qq.com/cgi-bin/musicu.fcg?-=getplaysongvkey2684794923029614&g_tk=1216837817&loginUin=254795854&hostUin=0&format=json&inCharset=utf8&outCharset=utf-8&notice=0&platform=yqq.json&needNewCode=0&data=%7B%22req%22%3A%7B%22module%22%3A%22CDN.SrfCdnDispatchServer%22%2C%22method%22%3A%22GetCdnDispatch%22%2C%22param%22%3A%7B%22guid%22%3A%229296374606%22%2C%22calltype%22%3A0%2C%22userip%22%3A%22%22%7D%7D%2C%22req_0%22%3A%7B%22module%22%3A%22vkey.GetVkeyServer%22%2C%22method%22%3A%22CgiGetVkey%22%2C%22param%22%3A%7B%22guid%22%3A%229296374606%22%2C%22songmid%22%3A%5B%22001vBzhR19LKRQ%22%5D%2C%22songtype%22%3A%5B0%5D%2C%22uin%22%3A%22254795854%22%2C%22loginflag%22%3A1%2C%22platform%22%3A%2220%22%7D%7D%2C%22comm%22%3A%7B%22uin%22%3A1234567890%2C%22format%22%3A%22json%22%2C%22ct%22%3A24%2C%22cv%22%3A0%7D%7D

新的接口应该可用，周末试一下提交

**Comment by sunzongzheng** [comment]
@wednesday 这个还是web版接口，我上次测试是只能听web版QQ音乐允许听的歌，而我测试了好几首歌都无法听，比如周杰伦的，就没有更新。
我刚刚再次做了测试，发现可听歌曲还是很多的，我先更新这个接口了。

**Comment by sunzongzheng** [comment]
已更新最新版web接口，如果有更好的解决方案会继续追加

**Comment by wednesday** [comment]
@sunzongzheng 你速度太快了，至少这个能放一部分歌曲，不能放的大部分是要购买的歌曲。

**Comment by sunzongzheng** [comment]
@wednesday 这个issues创建那天我就本地改好了，感觉效果太差，也没找到更好的方案就没提交 ~

**Comment by lokve** [comment]
感谢😘
