### ISSUE TITLE
虾米音乐获取歌手的信息有瑕疵

### ISSUE THREAD

**Issue by JohnSmith0602** [sunzongzheng/musicApi#15]
我使用关键词'一生所爱'调用 searchSong，会发现返回的结果中， xiami 对应的[一首歌](https://www.xiami.com/song/ckB1Wf7591)，api 返回的 artists 是 ['原声带']，而从网页上能看到歌曲页面显示的歌手信息是正确的 ['卢冠廷'、'莫文蔚']。我进一步跳到虾米这张专辑的页面，发现它的歌手信息就是'原声带'。

猜测代码的逻辑是取的专辑页面的歌手名。想问在不增加额外请求的前提下，有可能直接取到更正确的歌曲页面的歌手信息吗？

**Comment by sunzongzheng** [comment]
目前用的搜索接口没有返singer信息，只有artist信息。
目前最新版 web版虾米 接口返回的artist_name也是`原声带`，但是页面上用的是singer。

需要更换接口才行，稍后我更新一下~

**Comment by JohnSmith0602** [comment]
虾米都没了，关了吧。
