### ISSUE TITLE
[需求]查询歌曲结果携带指向各平台的歌曲页面的 url

### ISSUE THREAD

**Issue by JohnSmith0602** [sunzongzheng/musicApi#16]
这个是我在使用中碰到的具体需求，我希望用户搜索歌曲后有机会跳到歌曲在对应平台的外链，我期待的数据结构大概是这样的：
```javascript
{
  songs: [{
    name: '芳华绝代',
    url: 'https://y.qq.com/n/yqq/song/001IFoUn3oeFys.html',
    album: {
      cover: '...',
      url: 'https://y.qq.com/n/yqq/album/000xQ2Zy44PJ0g.html'
    }
  }]
}
```

我刚才看了下 QQ 音乐目前接口的返回数据，其中带的 mid 是能用来拼接 url 的。不知道 api 可以考虑添加上这两处 url 参数吗？我可以来提 PR～

**Comment by sunzongzheng** [comment]
可以，欢迎pr
不过字段名我推荐用`link`，`song's url`感觉会有歌曲资源地址的歧义

**Comment by JohnSmith0602** [comment]
@sunzongzheng ok

**Comment by JohnSmith0602** [comment]
@sunzongzheng 给你的 163 邮箱发了封邮件，请查收～

**Comment by sunzongzheng** [comment]
刚刚竟然没贴项目地址，尴尬…
https://github.com/sunzongzheng/music <https://github.com/sunzongzheng/music>

**Comment by sunzongzheng** [comment]
https://github.com/sunzongzheng/musicApi/pull/17 resolved
