### ISSUE TITLE
除了searchSong 这一个接口其他貌似都无法以web方式获得json

### ISSUE THREAD

**Issue by hugetiny** [sunzongzheng/musicApi#18]
```
https://suen-music-api.leanapp.cn/?method=searchSong&params=[{%22keyword%22:%22nujabes%22}]
```
search song是可以的
换了几个其他接口 都是按照method=getComment&params=[{...}]请求，都不行

**Comment by sunzongzheng** [comment]
确实有几个不行，但是应该是接口失效了，不是使用方式的问题。具体使用方式见下面几个示例，params就是函数的arguments

https://suen-music-api.leanapp.cn/?vendor=qq&method=getSongUrl&params=[7876962]

https://suen-music-api.leanapp.cn/?vendor=qq&method=getSongDetail&params=[7876962]

https://suen-music-api.leanapp.cn/?vendor=qq&method=getArtistSongs&params=[4558]

**Comment by hugetiny** [comment]
这个不修了？

**Comment by sunzongzheng** [comment]
我这边测试都正常，如果有问题请提供详细的调用方式及参数

https://suen-music-api.leanapp.cn/?vendor=qq&method=getLyric&params=[237773700]

**Comment by hugetiny** [comment]
改成用数组请求后貌似大多数都成功了，有什么IM可以交流下吗？
我想整合现在的bilibili音频和咪咕音乐进来，很多主流歌手的咪咕都能听，bilibili音频也起来了
类似下面这个项目的概念，多加几个平台
https://github.com/listen1/listen1-api

**Comment by sunzongzheng** [comment]
https://github.com/sunzongzheng/music#%E7%AE%80%E4%BB%8B
IM见上面项目介绍的交流群

1.x版本暂时不考虑增加音源了，2.0重构后再加入，现在文档、pr流程、接口字段结构等还有很多问题，等2.0版本一起完善了再做。你有需求的话先在你的fork分支做吧

**Comment by hugetiny** [comment]
哦好，2.0原来预定有哪些主要的变化？

**Comment by sunzongzheng** [comment]
- 使用typescript
- 内部不再try catch
- 函数名、返回字段调整，例如不再有quality、cp字段，用maxbr字段取代
- musicApi实例上不再挂载方法，只提供vendor的引用

https://github.com/sunzongzheng/musicApi/tree/v2

**Comment by hugetiny** [comment]
http://localhost:3001/?vendor=netease&method=getComment&params=[6452]
getComment 传歌手id 随便怎么样都是空的返回
