### ISSUE TITLE
searchSongs返回数据的total总是0

### ISSUE THREAD

**Issue by hugetiny** [sunzongzheng/musicApi#20]
searchSongs返回数据的total总是0，不管有没有查到

**Comment by sunzongzheng** [comment]
https://suen-music-api.leanapp.cn/?vendor=qq&method=searchSong&params=%5B%7B%22keyword%22:%22%E5%91%A8%E6%9D%B0%E4%BC%A6%22%7D%5D
这个就不是0。

提供一下请求参数

**Comment by hugetiny** [comment]
奇怪 今天又正常了，先关闭吧，也不知道啥时候能重现
