### ISSUE TITLE
文档里面这个不对：JSON.stringfy([param1, param2])

### ISSUE THREAD

**Issue by hugetiny** [sunzongzheng/musicApi#21]
JSON.stringfy任何数组都是undefined
应该是JavaScript encodeURIComponent() 函数吧？

**Comment by sunzongzheng** [comment]
![image](https://user-images.githubusercontent.com/12635613/69108851-e32b2980-0ab0-11ea-9ecb-4e4d92d2d456.png)

**Comment by hugetiny** [comment]
嗯 这个刚才搞错了，漏了一对括号
