### ISSUE TITLE
咨询一下是否有版权相关的信息，对应哪个字段？

### ISSUE THREAD

**Issue by JohnSmith0602** [sunzongzheng/musicApi#25]
你好，我想通过 API 知道一首歌在各个平台是否有版权，或者是不是 vip 才可听，或者是付费歌曲。因为缺少相关的文档，想问下目前的返回值中也这些信息字段吗？谢谢。

**Comment by sunzongzheng** [comment]
cp字段，true代表不能听，但是现在可能已经不太准

**Comment by david-ying-chan** [comment]
cp 的「不能听」是什么逻辑呢，为什么现在不准了呢？

**Comment by sunzongzheng** [comment]
不能听就是你上面说的平台无版权或需要vip。按我的经验来说，这个字段平台改的较为频繁，要准确很难

**Comment by JohnSmith0602** [comment]
谢谢～
