### ISSUE TITLE
vue中使用musicApi的函数报跨域错误怎么搞？

### ISSUE THREAD

**Issue by CGPer** [sunzongzheng/musicApi#26]
vue中使用musicApi报跨域错误：
`Access to fetch at 'https://music.163.com/weapi/cloudsearch/get/web' from origin 'http://localhost:8080' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.`
有人遇到吗？网上找好久也找不到解决办法

**Comment by dezhishen** [comment]
`index.html`
```
...
  <head>
     ...
    <meta name="referrer" content="never">
    <meta name="referrer" content="no-referrer">
  </head>
```

试了下,只能解决播放链接无法播放的问题...

**Comment by sunzongzheng** [comment]
跨域问题需要服务端配合允许跨域或使用不跨域的方式，纯前端是无法解决的。

可以使用文档中的`api server`的方式部署到服务器，这种方式下服务端已经设置了允许跨域

**Comment by sunzongzheng** [comment]
先关闭了，有问题可以再打开

**Comment by CGPer** [comment]
@sunzongzheng 已解决了跨域问题。请问一下貌似之前QQ音乐挂了，现在这个接口能用吗？

**Comment by sunzongzheng** [comment]
> @sunzongzheng 已解决了跨域问题。请问一下貌似之前QQ音乐挂了，现在这个接口能用吗？

我这边测试ok
