### ISSUE TITLE
Native实现Http Engine

### ISSUE THREAD

**Issue by jchsir** [sunzongzheng/musicApi#4]
有在ios上测试过fly的 Native实现Http Engine 吗？

**Comment by jchsir** [comment]
求ios demo

**Comment by sunzongzheng** [comment]
还真没测试过...没有ios开发者资源...

**Comment by jchsir** [comment]
刚写了一个oc的demo可以跑通，有一个坑是fly的，改了fly的源码才可以跑通，回头分享一下。fly对dsbridge的处理有问题，disbridge自己对返回值做了转json处理，fly又做了一遍，导致错误。

**Comment by sunzongzheng** [comment]
可以，期待分享
