### ISSUE TITLE
问下怎么用呀？调用不了呢？

### ISSUE THREAD

**Issue by Guidozijef** [sunzongzheng/musicApi#5]

**Comment by sunzongzheng** [comment]
什么环境？Nodejs只需要引入包然后直接调用方法就行了
````js
import musicApi from '@suen/music-api'

const data = await musicApi.searchSong('周杰伦')
console.log(data)
````

**Comment by Guidozijef** [comment]
vue项目，node环境到底是什么意思?能教教我怎么用吗?我qq，913497146------------------ 原始邮件 ------------------
发件人: "Suen"<notifications@github.com>
发送时间: 2019年5月2日(星期四) 晚上8:33
收件人: "sunzongzheng/musicApi"<musicApi@noreply.github.com>;
抄送: "Guidozijef"<913497146@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [sunzongzheng/musicApi] 问下怎么用呀？调用不了呢？ (#5)



什么环境？Nodejs只需要引入包然后直接调用方法就行了
 import musicApi from '@suen/music-api' const data = await musicApi.searchSong('周杰伦') console.log(data)
 
&mdash;

**Comment by sunzongzheng** [comment]
由于浏览器安全限制，纯前端无法使用

**Comment by Guidozijef** [comment]
node环境是什么?必须要有服务器是不是才可以?------------------ 原始邮件 ------------------
发件人: "Suen"<notifications@github.com>
发送时间: 2019年5月2日(星期四) 晚上9:57
收件人: "sunzongzheng/musicApi"<musicApi@noreply.github.com>;
抄送: "Guidozijef"<913497146@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [sunzongzheng/musicApi] 问下怎么用呀？调用不了呢？ (#5)



由于浏览器安全限制，纯前端无法使用
 
&mdash;

**Comment by sunzongzheng** [comment]
https://nodejs.org/zh-cn/
native客户端不需要服务器

**Comment by Guidozijef** [comment]
这个我下载了，npm都安装好了------------------ 原始邮件 ------------------
发件人: "Suen"<notifications@github.com>
发送时间: 2019年5月2日(星期四) 晚上10:21
收件人: "sunzongzheng/musicApi"<musicApi@noreply.github.com>;
抄送: "Guidozijef"<913497146@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [sunzongzheng/musicApi] 问下怎么用呀？调用不了呢？ (#5)



https://nodejs.org/zh-cn/
 native客户端不需要&#x670D;务器
 
&mdash;

**Comment by sunzongzheng** [comment]
nodejs按照示例引入并使用就可以了，前端无法使用这个包
