### ISSUE TITLE
请问下Leancloud参数params是通过怎样的格式传递的呢？

### ISSUE THREAD

**Issue by zhanggangbz** [sunzongzheng/musicApi#6]
leancloud部署后参考您的源码，猜了一些参数
我的params送入的是这样的格式[{"id":4}]
![image](https://user-images.githubusercontent.com/13991894/57762931-00162700-7733-11e9-8427-19dd903441f0.png)

但是传递到qq/index.js中的getTopList(id)方法，通过
console.log(id);
打印出的id此时的值为：
{ id: 4 }
该值会导致qq/index.js中的getTopList方法出错，只能修改您的代码，把该方法中的id修改为id.id才能正常返回
nodejs小白一个
请问下，我传递的参数params的样式是不是有问题

**Comment by sunzongzheng** [comment]
传递的值就是`JSON.stringify(arguments)`

`getTopList`的函数签名是这样的`async getTopList(id)`
所以函数执行时 `arguments` = [id]
JSON.stringify(arguments) = "[id]"

所以postman里你写`params: [4]`就可以了
