### ISSUE TITLE
没有获取专辑列表，专辑详情也是错误的

### ISSUE THREAD

**Issue by stoneWeb** [sunzongzheng/musicApi#7]
没有这个方法 `getAlbumSongs `
`getAlbumDetail `这个一直报错！
添加一下专辑列表吧

**Comment by sunzongzheng** [comment]
getAlbumDetail会返回专辑详情和歌曲列表。提供一下报错信息？

**Comment by stoneWeb** [comment]
qq的接口返回：
```
{ status: false,
  msg: '请求结果错误',
  log: ' {"code":1101,"subcode":1101,"message":"para error!"}' }
```
这个应该返回什么？看起来是返回一个专辑的详细信息以及歌曲列表，但是还是没有获取某位歌手的专辑列表。

**Comment by sunzongzheng** [comment]
参数也请提供一下，获取成功的话data会有数据，getAlbumDetail是获取专辑详情，getPlaylistDetail是获取歌单详情。
https://github.com/sunzongzheng/musicApi/blob/master/src/music-api.js

**Comment by sunzongzheng** [comment]
目前没有获取歌手专辑列表接口，专辑id只能从其他接口获取

**Comment by stoneWeb** [comment]
```
 album:
   { id: 8217,
     name: 'XXX',
     cover: 'https://XXX.jpg' },
  artists: [ { id: 4558, name: 'XXX' } ],
  name: 'XXX',
  id: 97740,
  cp: false,
  dl: false,
  quality: { '192': false, '320': false, '999': false },
  mv: 't0029vvcjv6' }
```
`musicApi.qq.getAlbumDetail({id: 8217, offset: 0, limit: 10})`

**Comment by sunzongzheng** [comment]
https://github.com/sunzongzheng/musicApi/blob/33c2155b800e09cc2975a8881ad7188c05ebce01/src/qq/index.js#L314-L337
musicApi.qq.getAlbumDetail(8217)
